#!/usr/bin/env bash

set -e

SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOTDIR="$(git -C "$SCRIPTDIR" rev-parse --show-toplevel)"
flag=0
cat > "${ROOTDIR}/AUTHORS" <<- EOF
	# File generated by create_authors.sh. DO NOT EDIT.
	# This file lists all contributors to the repository.
	# See create_authors.sh to make modifications.

	$(git -C "$ROOTDIR" log --format='%aN <%aE>' | LC_ALL=C.UTF-8 sort -uf)
	
EOF
flag=1
if (($flag == 1))
then
	echo "Authors file generated successfully"

fi
if (($flag == 0))
then
	echo "Unable to create Authors file"
fi
